version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=instalando_cali_db
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=developer@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
