version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: data_base_container
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=instalando_cali_db
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=developer@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
